Disable 1cycle because it broke Run6
Run6: https://ml.azure.com/experiments/id/f3e2b900-5d3e-4900-9e10-841a8766cd49/runs/training-junkyard-speedup_1624545975_ce7849a2?wsid=/subscriptions/9b5bbfae-d5d1-4aae-a2ca-75159c0c887d/resourcegroups/cgm-ml-prod-we-rg/workspaces/cgm-ml-prod-we-azml&tid=3a27c573-ec1a-4734-9cd3-3208af51794b#outputsAndLogs

TypeError: x and y must have the same dtype, got tf.int64 != tf.float32